com:
  challenge:
    sales:
      statistics:
        period_in_sec: 60
debug: false
logging:
  level:
    root: info
server:
  port: 8080
#  tomcat:
#    max-threads: 4
#    max-connections: 4
#    accept-count: 12
